feat : axios instance
depromeet/bbo-gak-client pull request #12
Opened 2024-07-19 15:52 UTC by eunbeann

## 1. 무슨 이유로 코드를 변경했나요?
Axios Instance를 만들었습니다

## 2. 어떤 위험이나 장애를 발견했나요?
-

## 4. 완료 사항
- AxiosInstance
    - baseURL은 환경변수로 관리 되도록 했습니다.
    - 👞 요청 제한 시간 10초로 설정해두었습니다.
    - [withCredentials](https://inpa.tistory.com/entry/AXIOS-%F0%9F%93%9A-CORS-%EC%BF%A0%ED%82%A4-%EC%A0%84%EC%86%A1withCredentials-%EC%98%B5%EC%85%98#%F0%9F%8D%AA_withcredentials_%EC%98%B5%EC%85%98%EC%9C%BC%EB%A1%9C_%EC%BF%A0%ED%82%A4_%EB%B3%B4%EB%82%B4%EA%B8%B0)을 사용해서 쿠키/ 인증 헤더 정보를 포함시켜 요청합니다.
    
- interceptors.request
    - interceptor.request로 헤더에 accessToken을 추가해줍니다.
    - `config.headers.common['Authorization']` 모든 요청에 토큰을 담도록 합니다. 

- interceptors.response
    - 우선은 개발 환경일 때만 콘솔에 response 값을 출력하도록 했습니다. 혹시 디버깅에 불편할 것 같다면 삭제하겠습니다.
    - 구체적인 서버 API 명세 나온 후 refreshToken 업데이트 로직 등 기능 추가 예정입니다.

## 5. 추가 사항 / 코드 리뷰 받고 싶은 부분
<br>
빠져야하거나, 추가되어야하는 부분 편하게 말해주세요.

2024-07-19 16:10 UTC, qkrdmstlr3 commented on src/apis/http.ts
> +  (config) => {
잘 몰라서 질문.. http라는 이름이 너무 제너럴한 것 같은데, 보통 많이 쓰이는 이름인가요?
axiosInstance를 그대로 사용하지 않고 이름을 지어주는 이유가 궁금합니다!

2024-07-19 16:26 UTC, Collection50 requested changes
고생하셨습니다 👍 

코멘트 남겨드렸습니다 !!

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +  (config) => {
네 보통 자주 쓰이긴 합니다 !
혹은 api로도 사용됩니다 !

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +}
전달드린 코드 참고하셔서 변경하시면 좋을 것 같아요 !
제네릭 타입을 명확히 추론할 수 있도록 unknown, any를 지양하시면 좋을 것 같습니다 !

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +    if (!config.headers) return config;
조건문의 형식을 통일하시면 좋을 것 같아요 !
`{}`를 사용하는 형식이 좋을 것 같은데 어떻게 생각하시나요 ??

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +    }
config의 set함수를 쓰는게 좋을 것 같은데 어떻게 생각하시나요??

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +  },
`ErrorBoundary`를 사용할 예정이므로 에러 그대로를 throw 하면 좋을 것 같아요 !!!

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +    !isProd() && console.log(response);
조건문을 추가하는게 더 좋을 것 같아요 !
airbnb eslint에서도 권장하는 방법입니다 !

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +  },
위 throw 리뷰와 같습니다 !

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +    }
이 조건문은 31번 라인 전으로 추가해도 될 것 같습니다

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +}
get, post, put, patch, delete 객체를 명확하게 반환하면 interface를 반환하지 않고도 올바르게 추론할 수 있다고 생각합니다 !!
어떻게 생각하시나요??

2024-07-19 16:26 UTC, Collection50 commented on src/utils/common.ts
> +// usage: isProd();
불필요한 주석이라고 생각합니다

어떻게 생각하시나요??

2024-07-19 16:26 UTC, Collection50 commented on src/apis/http.ts
> +    }
Cool ! 👍

2024-07-19 16:32 UTC, qkrdmstlr3 commented on src/utils/common.ts
> +// usage: isProd();
함수이름에서 환경변수를 사용한다는 것을 유추하기 어려운 것 같아요. isProdEnv나 isProductionEnv 정도로 풀어쓰는것은 어떤가요?

2024-07-19 16:35 UTC, qkrdmstlr3 commented on src/apis/http.ts
> +    !isProd() && console.log(response);
어떤 목적으로 개발모드에서는 항상 찍어줘야하는지 궁금해요!

2024-07-19 16:45 UTC, woo-jk reviewed
고생하셨습니다~!!!! 코멘트 한 번만 확인 부탁드려요~

2024-07-19 16:45 UTC, woo-jk commented on src/apis/http.ts
> +  },
error로 특별한 로직 안하면 두 번째 콜백은 없어도 되지 않나요!?

2024-07-19 16:45 UTC, woo-jk commented on src/apis/http.ts
> +    !isProd() && console.log(response);
저도 같은 의견으로, if문을 쓰는게 더 가독성이 좋을 것 같아요!

2024-07-19 16:45 UTC, woo-jk commented on src/apis/http.ts
> +}
axios 자체의 메소드(get, post 등)에서도 타입 지정이 되어있는데, 굳이 같은 타입을 한번 더 인터페이스로 감싼 이유가 궁금합니다!!

2024-07-19 16:45 UTC, woo-jk commented on src/apis/http.ts
> +    return response.data;
data를 반환하면 http를 사용하는 측에서 response의 다른 요소들(headers, status 등)을 사용하지 못할 것 같은데, 확장성 측면에서 괜찮을지 의견 묻고 싶어요~!

2024-07-19 19:45 UTC, eunbeann commented on src/apis/http.ts
> +    if (!config.headers) return config;
너무 좋아요!
반영했습니다 [e1b4f79](https://github.com/depromeet/bbo-gak-client/pull/12/commits/e1b4f795c1ccbec9637539ba694aa1a6d13193a8)

2024-07-19 19:51 UTC, eunbeann commented on src/apis/http.ts
> +    !isProd() && console.log(response);
@Collection50 @woo-jk 반영했습니다 감사합니다~!

[e1b4f79](https://github.com/depromeet/bbo-gak-client/pull/12/commits/e1b4f795c1ccbec9637539ba694aa1a6d13193a8)


@qkrdmstlr3 개발환경에서 response 값 잘 들어오는지 바로 확인하기 위함입니다! 이렇게 많이 쓰기도하고 있으면 편할 것 같아서 추가해뒀습니다! PR에도 남겼는데 혹시 오히려 콘솔창이 지저분해질 것 같으면 편하게 말해주세요!

2024-07-19 19:52 UTC, eunbeann commented on src/apis/http.ts
> +  },
[ea7ac3e](https://github.com/depromeet/bbo-gak-client/pull/12/commits/ea7ac3e3071365b0c4b8c710060d897076cb7909)

반영했습니다! 감사합니다~

2024-07-19 19:53 UTC, eunbeann commented on src/apis/http.ts
> +  },
[ea7ac3e](https://github.com/depromeet/bbo-gak-client/pull/12/commits/ea7ac3e3071365b0c4b8c710060d897076cb7909)

감사합니다 (--)(__)

2024-07-19 19:58 UTC, eunbeann commented on src/utils/common.ts
> +// usage: isProd();
@Collection50 네 직관적으로 사용 가능한 유틸이니 삭제하는 편이 더 좋겠네요 감사합니다 [9c87a53](https://github.com/depromeet/bbo-gak-client/pull/12/commits/9c87a533d3da61e6a4352a2e52bec3b8725ecdfb)

@qkrdmstlr3 많이 쓰이는 함수명이라 생각해 썼는데 Env가 붙는 게 훨씬 직관적이네요. 저희 컨벤션에 풀어쓰기도 있었던 것으로 기억해서 `isProductionEnv`로 반영했습니다! [78f96a2](https://github.com/depromeet/bbo-gak-client/pull/12/commits/78f96a21687562266892f2aa848bbfd96d25fd75)

2024-07-23 16:40 UTC, eunbeann commented on src/apis/http.ts
> +    return response.data;
흠 요거 생각을 못했네요 
우선 response로 반환할 수 있도록 수정했습니다!
[e0966d0](https://github.com/depromeet/bbo-gak-client/pull/12/commits/e0966d0756f9c071d4215997587aa0888e310d19)

2024-07-23 16:42 UTC, eunbeann commented on src/apis/http.ts
> +}
타입 추론으로 타입을 정의하는 방법에 대해서 생각해보지 못했었네요 흠;;
성민님이 도움 주셔서 수정했습니다 [db53b51](https://github.com/depromeet/bbo-gak-client/pull/12/commits/db53b51bc895ee78338b555e98e4fe15ab1d330d)

2024-07-23 16:42 UTC, eunbeann commented on src/apis/http.ts
> +}
감사합니다 수정했습니다 [db53b51](https://github.com/depromeet/bbo-gak-client/pull/12/commits/db53b51bc895ee78338b555e98e4fe15ab1d330d)

2024-07-23 16:46 UTC, eunbeann commented on src/apis/http.ts
> +    }
config.header.common 사용 시 모든 요청에 적용된다고 알고 있어서, 저희 서비스에서는 토큰이 안들어가는 요청이 없다고 판단해서 common 사용했는데 혹시 어떻게 생각하시나요?!

++ 해당 조건문이 31번 라인 전으로 들어가도 로직상 큰 차이 없을 것 같은데 혹시 이유를 알 수 있을까요?!

2024-07-24 15:00 UTC, qkrdmstlr3 approved these changes
저는 문제없습니다! [요 댓글](https://github.com/depromeet/bbo-gak-client/pull/12#discussion_r1688388980)에 대한 답변만 받으시고, 머지하면 될 것 같아요!

2024-07-25 01:56 UTC, woo-jk approved these changes

2024-07-25 04:41 UTC, Collection50 commented on src/apis/http.ts
> +    }
`common`을 통해 모든 요청에 들어갈 수 있다고 생각합니다 !! 저는 library의 제공 함수를 쓰는 것이 가독성 측면이나 통일성 측면에서 좋다고 생각해서 남긴 리뷰였습니다!!

<br/>

> 해당 조건문이 31번 라인 전으로 들어가도 로직상 큰 차이 없을 것 같은데 혹시 이유를 알 수 있을까요?!

config.headers가 존재하지 않더라도, token이 존재한다면 headers 내부에 담아야 한다고 생각했기 때문이었습니다 !!

2024-07-25 04:42 UTC, Collection50 commented
긴 PR 작업하시느라 고생하셨습니다 !!!

2024-07-25 04:42 UTC, Collection50 approved these changes

2024-07-28 10:24 UTC, merged